(set! imagine #c(2 5))
(set! imagine2 #c(2 7))
'tests
(realpart imagine)
(realpart 7)
(imagpart imagine)
(imagpart 8)
(+ imagine 2)
(+ imagine imagine2)
(- imagine imagine2)
(* imagine imagine2)
(/ imagine imagine2)
(/ imagine 3)
(* 6 imagine2)